// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLA-rikePrW8jNXVqKZtIVoHk3wJTNhlM',
    appId: '1:634815997478:web:98d44c784f3bf5cef1e8e7',
    messagingSenderId: '634815997478',
    projectId: 'event-sphere-app',
    authDomain: 'event-sphere-app.firebaseapp.com',
    storageBucket: 'event-sphere-app.firebasestorage.app',
    measurementId: 'G-JZHFZQNDD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPb3QTU50bcVdok-Se8U8k1kf46Lt8as4',
    appId: '1:634815997478:android:389dac06f75d3301f1e8e7',
    messagingSenderId: '634815997478',
    projectId: 'event-sphere-app',
    storageBucket: 'event-sphere-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB0e1Oq6wCjDTNI038i4KwMo1_cZKijxA',
    appId: '1:634815997478:ios:6236e9ddd81405f0f1e8e7',
    messagingSenderId: '634815997478',
    projectId: 'event-sphere-app',
    storageBucket: 'event-sphere-app.firebasestorage.app',
    iosBundleId: 'com.example.eventSphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB0e1Oq6wCjDTNI038i4KwMo1_cZKijxA',
    appId: '1:634815997478:ios:6236e9ddd81405f0f1e8e7',
    messagingSenderId: '634815997478',
    projectId: 'event-sphere-app',
    storageBucket: 'event-sphere-app.firebasestorage.app',
    iosBundleId: 'com.example.eventSphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLA-rikePrW8jNXVqKZtIVoHk3wJTNhlM',
    appId: '1:634815997478:web:fb2efe62a90bb468f1e8e7',
    messagingSenderId: '634815997478',
    projectId: 'event-sphere-app',
    authDomain: 'event-sphere-app.firebaseapp.com',
    storageBucket: 'event-sphere-app.firebasestorage.app',
    measurementId: 'G-RR5LXN0P3J',
  );
}
